
services:
  app:
    build: .
    volumes:
      - .:/var/www
    depends_on:
      - db

  web:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: roberto
      MYSQL_PASSWORD: citaclick
      MYSQL_ROOT_PASSWORD: citaclick
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
